name: Defi File Storage CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Compile Solidity contracts
        run: npx truffle compile # Assuming you use Truffle for compiling Solidity contracts

      - name: Run tests
        run: npx truffle test # Assuming you have tests defined in Truffle

      - name: Deploy smart contracts
        run: npx truffle migrate --network <your_network> # Replace <your_network> with your actual network
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: Notify deployment status
        run: echo "Deployment complete"
